language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:~0.6.1 --prefer-source --no-interaction --dev

script: vendor/bin/phpunit -c phpunit.xml --coverage-text

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == *5.6* ]]; then php vendor/bin/coveralls -v; fi

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fash_finish: true
