language: php

sudo: false

git:
  submodules: true

php:
  - 7.1
  - 7.2

env:
  global:
    - setup=basic

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true

before_script:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit -c phpunit.xml

matrix:
  include:
    - php: 7.1
      env: setup=lowest
    - php: 7.1
      env: setup=stable
  fast_finish: true
