language: php

sudo: false

git:
  submodules: true

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  matrix:
    - setup=basic
    - setup=lowest
    - setup=stable

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true

before_script:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit -c phpunit.xml --testdox --verbose

matrix:
  fast_finish: true
